
package clase2.ejemplo2;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://soa.empresa.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TimeServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soa.empresa.com/TimeServer/getTimeServiceAsStringRequest", output = "http://soa.empresa.com/TimeServer/getTimeServiceAsStringResponse")
    public String getTimeServiceAsString();

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soa.empresa.com/TimeServer/getTimeServiceAsLongRequest", output = "http://soa.empresa.com/TimeServer/getTimeServiceAsLongResponse")
    public long getTimeServiceAsLong();

}
